### ISSUE TITLE
[doc] 'docs/guides/development.md' not found

### ISSUE THREAD

**Issue by princejwesley** [dekujs/deku#289] opened 2015-11-24 05:55 UTC
`docs/guides/development.md` file is not found.

Below links are broken in `Readme.md` file:

- [Contributing to Deku](https://github.com/dekujs/deku/blob/master/docs/guides/development.md)

..Learn how to build and work on Deku [in the documentation](https://github.com/dekujs/deku/blob/master/docs/guides/development.md).

**Comment by tejasmanohar** [comment] 2015-11-30 06:57
Should be closed as a duplicate of #266

**Comment by princejwesley** [comment] 2015-11-30 07:01
@tejasmanohar Yes, it is. can you update the other ticket with `Contributing to Deku` link which is also broken.

**Closed** 2015-11-30 07:01 UTC

**Comment by tejasmanohar** [comment] 2015-11-30 07:26
same file
