### ISSUE TITLE
Question: how do I get `dispatch` on the model?

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#322] opened 2015-12-29 07:52 UTC
`render`, `onUpdate` and other lifecycle hooks receive a model:

```
render ({ props, dispatch, path }) { ... }
onCreate ({ props, dispatch, path }) { ... }
```

But it seems the actual arguments of the model are:

```
{ props, children, path, context }
```

**Comment by anthonyshort** [comment] 2015-12-29 18:54
This is probably a duplicate of #323. That's fixed, but it would have prevented the dispatch function being passed down correctly.

**Comment by rstacruz** [comment] 2015-12-29 22:39
Haha cute, my code made it to the tests :P

**Closed** 2015-12-30 01:18 UTC
